### ISSUE TITLE
Column number in mtx does not match the barcodes file for sample "adipose/GSM3711758"

### ISSUE THREAD

**Issue by Bondada20** [cellatlas/human#1]
Hello,

Thanks for the effort put into the Commons Cell Atlas, which my lab has started to explore.

I was able to read the count matrices for all samples into R, except for adipose/GSM3711758, which generated the following error:
Error in `map()`:
ℹ In index: 1.
Caused by error:
! Matrix has 2802 columns but found 3790 barcodes. Try increasing `skip.cell`. 

As you can see, the number of columns in the matrix does not match the number of barcodes.

**Comment by sbooeshaghi** [comment]
Thank you for pointing this out! I have fixed this in https://github.com/cellatlas/human/commit/05f798d960c8c9eee5ae7e4c20af2d8501e0c6cc.
