### ISSUE TITLE
mx_filter.py

### ISSUE THREAD

**Issue by tanushk20** [cellatlas/human#2]
Hi there,

Thanks a lot for CCA. We wanted to do some analysis on some different datasets, and were trying to realign them to the same set of genes as in the CCA. To do this, we have been trying to use the code in "preprocess.ipynb" notebooks present in each GEO sample folder. However, running this notebook requires the "mx_filter.py" file, but we are not able to find this file anywhere. Can you kindly point us to this file, if it is available? 

Thanks a lot!

**Comment by sbooeshaghi** [comment]
Thanks for the feedback. We have consolidated all of the mx utilities into a python package. Please see https://github.com/sbooeshaghi/mx/ the `mx filter` command which can be executed from the command line or from a python environment.
